# -*- coding: utf-8 -*-
# ---
# jupyter:
#   jupytext:
#     formats: ipynb,py:light
#     text_representation:
#       extension: .py
#       format_name: light
#       format_version: '1.5'
#       jupytext_version: 1.10.2
#   kernelspec:
#     display_name: Python 3
#     language: python
#     name: python3
# ---

# # "Working in fastpages"
# > "Getting this site setup"
#
# - toc: false
# - branch: master
# - badges: false
# - comments: true
# - categories: [fastpages, jupyter]
# - image: "images/thumbnails/7538107210_cf213e2a7c_c.jpeg"
# - hide: false
# - search_exclude: false

# ![](my_icons/noun_waving_hello_3169895.png)

# ## Hello, World!

# Well that was relatively painless.
#
# Here's a site made out of (mostly) jupyter notebooks. This post is just a jupyter notebook. 😎 Thanks, [fastpages](https://github.com/fastai/fastpages)! 🚀

# ## What Was Easy

# - **Setup is a breeze**: fastpages made it really easy to setup from their repo. Using an auto-generated pull request, was able to get a new repo up and running with no trouble.
# - **Connect to existing stuff**: Connecting to GitHub Pages site [zachbogart.github.io](https://zachbogart.github.io/) was easy. Just set it as the `baseurl`.
# - **Tracking Notebooks**: Was worried that the use of jupyter notebooks to render the posts might mean that the `.ipynb` files have to be git tracked. This can be a pain cause there is a lot in each notebook, so running a notebook without changing code will still lead to git changes, which are difficult to parse without additional tools. 
#     - However, at least for this post, [jupytext](https://jupytext.readthedocs.io/en/latest/index.html) works like a charm!{% fn 1 %} Can work in jupyter notebooks, track python script versions of them, and have it all be rendered to a site. Super awesome. Hope it lasts...

# ## What Will Require More Understanding
#
# - **Handling Images**: For previous posts, I used images as thumbnails *and* at the start of each post. In my experimenting, was finding I had to copy the image in two places: `my_icons` in the `_notebooks` folder and in the `images` folder. Wondering if there is a cleaner way to include an image in just one place (the [docs](https://github.com/fastai/fastpages#setting-an-image-for-social-media) mention that the social media image can only be set under `images`).
# - **It's a big machine**: The repo can be pretty intimidating. There are a lot of folders that make it go and a bunch of files with "THIS FILE WAS AUTOGENERATED! DO NOT EDIT!" penciled in. Will take some getting used to, getting comfortable with the setup and knowing what parts I should touch. There are some files that I could burn myself on, so I will go slow, use oven mitts, and try not to void any warranties.

# I'll keep [the docs](https://github.com/fastai/fastpages#welcome-to-fastpages) handy. 
#
# Till next time!

# + [markdown] jupyter={"source_hidden": true}
# ![](https://media.giphy.com/media/G5h04AkAvAHcs/giphy.gif)
# -

# #### Image Credit
# - [waving hello](https://thenounproject.com/search/?creator=4129988&q=hello&i=3169895) by Zach Bogart from the [Noun Project](https://thenounproject.com/zachbogart/)
# - [Differential Analyzer](https://www.flickr.com/photos/nasacommons/7538107210/in/photolist-cu7LDG-cu7KiW-cubwMw-cu7Lim-cu7L1S-cu7L9d-bH9Ff6-kUBmeB-cubwDj-qAj3oW-cu7MDs-2hXAdPi-2jGCtk8-2jGCtj1-fpKVja-dWrkiU-dMAhAv-23Pqy53-dMFR2m-dMFRby-dMFRko-dMAhPP-dMFRaU-wLozW8-dMFTUW-2k3Gwre-2k3GwrE-oeuB1P-2k3Y9g1-2k3GwsG-2k3Xtps-2k3CGnm-2k3TEak-2k3Gwvs-2k3CGoi-2k3CGnX-2k3Gwsg-2k3Y9fp-2k3CGn1-2k3HdRZ-2k3Gwsr-2k3GwvN-2k3GwqC-2k3Gwr4-2k3YBEu-2k3Kuuo-2k3GwvC-2k3YBDT-2k3EYKc-2k3YBEV) from "NASA on The Commons" on Flickr Commons
#     - Cool Description: *Differential Analyzer built under the direction of Harold Mergler in the Instrument Research Section. The technician is preparing a data report. This equipment was located at the Lewis Flight Propulsion Laboratory, LFPL, now John H. Glenn Research Center at Lewis Field, Cleveland Ohio.*

# {{ '[Jupytext](https://github.com/mwouts/jupytext) is a super useful way to save off jupyter notebooks as other formats. I use it all the time. Pairing a notebook is easy and you can just set it and forget it. Note: If in [JupyterLab](https://jupyterlab.readthedocs.io/en/stable/), use "View > Activate Command Palette" or "Shift + Cmd + C" to "Pair..." a notebook format. Took me a while to find out how to do this! ' | fndetail: 1 }}


